services:
  # --- PostgreSQL (Shared) ---
  postgresql:
    image: docker.io/library/postgres:16-alpine
    # restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./init-shlink-db.sh:/docker-entrypoint-initdb.d/init-shlink-db.sh
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:-postgres}
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_DB: ${PG_DB:-authentik}
    env_file:
      - .env.docker

  # --- Redis (Shared) ---
  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    # restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis_data:/data

  # --- Authentik ---
  server:
    image: ghcr.io/goauthentik/server:2024.2.1
    # restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-postgres}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS:-postgres}
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    env_file:
      - .env.docker
    ports:
      - "${COMPOSE_PORT_HTTP:-9000}:9000"
      - "${COMPOSE_PORT_HTTPS:-9443}:9443"
    depends_on:
      - postgresql
      - redis

  worker:
    image: ghcr.io/goauthentik/server:2024.2.1
    # restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-postgres}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS:-postgres}
    # `user: root` is required for docker socket integration
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    env_file:
      - .env.docker
    depends_on:
      - postgresql
      - redis

  # --- Shlink ---
  shlink:
    image: shlinkio/shlink:stable
    # restart: unless-stopped
    environment:
      DEFAULT_DOMAIN: localhost:8080
      SHLINK_SERVER_API_KEY: ${SHLINK_SERVER_API_KEY}
      IS_HTTPS_ENABLED: "false"
      GEOLITE_LICENSE_KEY: ${GEOLITE_LICENSE_KEY}
      DB_DRIVER: postgres
      DB_USER: ${PG_USER:-postgres}
      DB_PASSWORD: ${PG_PASS:-postgres}
      DB_HOST: postgresql
      DB_NAME: shlink # Note: You might need to create this DB manually or via init script if it doesn't exist
      REDIS_SERVERS: tcp://redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
      - redis

volumes:
  database_data:
  redis_data:
